### PR TITLE
updating to ember 2.15 and getting rid of bower

### PR DESCRIPTION
**Pull request by feanor07**
I have updated to ember 2.15 while making `perfect-scrollbar` a node dependency instead of a bower dependency. this will also be a fix for issue #15.

### CODE REVIEW

**Comment by feanor07** [comment]
made previous commit pass travis build.

**Comment by feanor07** [comment]
the name of npm-package and ember project are different. this created some confusion; so I have fallen back to blueprint convention that had been committed originally.

**Comment by imanhodjaev** [comment]
@feanor07 thanks for this update did you test if npm package way works put well?
If it is then I would be happy to merge.

**Comment by feanor07** [comment]
do you mean installing the add-on via `npm install https://github.com/feanor07/ember-perfect-scroll --save-dev`; if this is the case it works. if it is something else; can you clarify it?

**Comment by imanhodjaev** [comment]
@feanor07 yes exactly, @fpauser thank you very much for review.

**Comment by feanor07** [comment]
@imanhodjaev it seems ok then; @fpauser thanks for the review.

**Comment by imanhodjaev** [comment]
✨🍰✨

**Comment by imanhodjaev** [comment]
@feanor07 thanks!

**Pull request merged**
